---
- name: Check firewalld status
  ansible.builtin.command:
    cmd: systemctl is-active firewalld
  register: firewalld_status
  changed_when: false
  failed_when: false


- name: Open HTTP port using firewall-cmd
  ansible.builtin.command:
    cmd: firewall-cmd --permanent --add-service=http
  register: firewall_http
  changed_when: "'success' in firewall_http.stdout"
  when:
    - firewalld_status.rc == 0


- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  when:
    - firewalld_status.rc == 0
    - firewall_http.changed
