---
- name: Configure Grafana repository
  ansible.builtin.yum_repository:
    name: grafana
    description: Grafana OSS
    baseurl: https://rpm.grafana.com
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://rpm.grafana.com/gpg.key
    sslverify: true

- name: Install Grafana
  ansible.builtin.dnf:
    name: grafana
    state: present
- name: Deploy Grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "0640"
  notify:
    - Restart grafana
  no_log: true
- name: Create Grafana datasource directory
  ansible.builtin.file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: root
    group: grafana
    mode: "0755"

- name: Configure Prometheus datasource
  ansible.builtin.template:
    src: datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yml
    owner: root
    group: grafana
    mode: "0640"
  notify:
    - Restart grafana
- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
    daemon_reload: true
