---
- name: Deploy application database secret manifest
  ansible.builtin.template:
    src: app-db-secret.yaml.j2
    dest: /tmp/app-db-secret.yaml
    owner: root
    group: root
    mode: "0600"
  no_log: true

- name: Apply application database secret
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/app-db-secret.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: secret_apply
  changed_when: >
    'created' in secret_apply.stdout or
    'configured' in secret_apply.stdout
  no_log: true

- name: Remove temporary secret manifest
  ansible.builtin.file:
    path: /tmp/app-db-secret.yaml
    state: absent
  no_log: true
