---
- name: Get current timezone
  ansible.builtin.command:
    cmd: timedatectl show --property=Timezone --value
  register: current_timezone
  changed_when: false


- name: Set system timezone
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ common_timezone }}"
  when:
    - current_timezone.stdout != common_timezone
